name: 'Print Wrangler Logs'
description: 'Prints Wrangler logs files if exist'
inputs:
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare API Token'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare Account ID'
    required: true
  CLOUDFLARE_ENVIRONMENT:
    description: 'Cloudflare Environment'
    required: true
    type: choice
    options:
      - preview
      - production
runs:
  using: 'composite'
  steps:
    - name: Migrate database
      uses: cloudflare/wrangler-action@v3.3.2
      with:
        wranglerVersion: '3.75.0'
        apiToken: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        workingDirectory: server
        preCommands:  |
          nl -w1 -s': ' wrangler.toml
        command: |
          d1 migrations apply ${{ inputs.CLOUDFLARE_ENVIRONMENT }} --remote --env ${{ inputs.CLOUDFLARE_ENVIRONMENT }}
        packageManager: yarn
      env:
        NO_D1_WARNING: true
        CI: true
        WRANGLER_LOG: debug
        WRANGLER_LOG_SANITIZE: false

    - name: Print wrangler extra logs on failure
      if: failure()
      uses: ./.github/actions/print-wrangler-logs
