/**
 * Public MCP connector documentation page (U13 of the connector-store
 * readiness plan).
 *
 * Reviewer contract: Anthropic's Software Directory Policy requires a
 * public documentation URL the reviewer can reach within ~10 minutes of
 * installing the connector, with (a) a connection guide, (b) the tool
 * catalog, (c) ≥3 example prompts, (d) a clear privacy + support surface.
 * Every section here exists to satisfy one of those requirements.
 *
 * Information architecture (NOT a flat 103-tool dump — per the D6
 * doc-review finding):
 *   1. Hero / one-line value prop
 *   2. Quickstart: Claude.ai custom-connector install with cross-origin
 *      AS-domain awareness + inline "If your install fails…" troubleshooting
 *   3. Scopes: 4-row table
 *   4. Example prompts: 3 cards (read, write, elicitation)
 *   5. Tool catalog: grouped by domain (Packs, Trips, Trails, ...), each
 *      tool rendered with scope chip + annotation chips
 *   6. Resources: 6 URIs
 *   7. Privacy + security: pointers to U12 pages
 *   8. Reviewer test account: pointer to submission-packet doc
 *   9. Footer: dev README + plan + runbook
 *
 * Post-refactor (2026-05-25) note: § 2 calls out the cross-origin AS
 * (api.packrat.world) explicitly so a reviewer or end user who notices
 * the domain switch during install has the expected explanation in
 * hand. The expandable troubleshooting block covers the common failure
 * modes from the refactor plan's HLD (CORS, redirect-strips-Authorization,
 * misconfigured client, refresh-token rotation) — operator-side detail
 * is in docs/mcp/runbook.md.
 *
 * Data source: the tool catalog is loaded from
 * `apps/landing/data/mcp-catalog.json`, generated by
 * `bun packages/mcp/scripts/dump-catalog.ts`. After any tool change
 * (new tool, rename, annotation tweak), rerun the script and commit
 * the regenerated JSON in the same PR — the page is RSC-only and
 * reads the JSON at build time.
 *
 * Styling: matches `apps/landing/app/privacy-policy/page.tsx` — same
 * container width, same heading hierarchy, same Tailwind tokens. No
 * new components introduced; reuse the landing site's vocabulary.
 */

import catalog from 'landing-app/data/mcp-catalog.json';
import Link from 'next/link';

export const metadata = {
  title: 'PackRat MCP Connector | PackRat',
  description:
    'Connect Claude or any MCP-capable client to PackRat — packs, trips, trails, gear, weather, and more — via OAuth-secured Streamable HTTP.',
  robots: { index: true, follow: true },
};

interface CatalogEntry {
  name: string;
  title: string;
  description: string;
  domain: string;
  classification: 'read' | 'write' | 'admin';
  annotations: {
    readOnlyHint: boolean | null;
    destructiveHint: boolean | null;
    idempotentHint: boolean | null;
    openWorldHint: boolean | null;
  };
}

interface CatalogShape {
  generatedAt: string;
  totalTools: number;
  counts: {
    byClassification: Record<'read' | 'write' | 'admin', number>;
    byDomain: Record<string, number>;
  };
  scopes: Array<{ name: string; description: string }>;
  endpoint: string;
  tools: CatalogEntry[];
}

// safe-cast: catalog JSON is generated by packages/mcp/scripts/dump-catalog.ts (a
// committed build artifact), so its shape is guaranteed at build time. No runtime
// user input flows through this value — introducing a zod schema would duplicate
// the existing TypeScript interface above without adding signal.
const typedCatalog = catalog as CatalogShape;

// Stable ordering for the rendered domain sections. Domains not listed
// here are appended alphabetically at the end (which only happens if
// `classifyDomain` in `dump-catalog.ts` introduces a new bucket).
const DOMAIN_ORDER = [
  'Account',
  'Packs',
  'Pack Templates',
  'Trips',
  'Trails',
  'Trail Conditions',
  'Weather',
  'Gear & Catalog',
  'Knowledge & Search',
  'Feed',
  'Guides',
  'Seasons',
  'Wildlife',
  'Uploads',
  'Admin & Analytics',
  'Database (Admin)',
] as const;

function groupedByDomain(tools: CatalogEntry[]): Array<[string, CatalogEntry[]]> {
  const groups = new Map<string, CatalogEntry[]>();
  for (const t of tools) {
    const list = groups.get(t.domain) ?? [];
    list.push(t);
    groups.set(t.domain, list);
  }
  // Sort each group alphabetically by tool name for stable rendering.
  for (const list of groups.values()) {
    list.sort((a, b) => a.name.localeCompare(b.name));
  }
  const ordered: Array<[string, CatalogEntry[]]> = [];
  const seen = new Set<string>();
  for (const domain of DOMAIN_ORDER) {
    const list = groups.get(domain);
    if (list && list.length > 0) {
      ordered.push([domain, list]);
      seen.add(domain);
    }
  }
  // Append any extra domains (defensive — should be empty in steady state).
  const extras = Array.from(groups.keys())
    .filter((d) => !seen.has(d))
    .sort();
  for (const d of extras) {
    const list = groups.get(d);
    if (list) ordered.push([d, list]);
  }
  return ordered;
}

function ScopeChip({ scope }: { scope: 'read' | 'write' | 'admin' }) {
  // Distinct color treatment per scope so a reviewer scanning the tool
  // catalog can see at a glance which tools each scope unlocks.
  const palette: Record<typeof scope, string> = {
    read: 'bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-100',
    write: 'bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-100',
    admin: 'bg-rose-100 text-rose-900 dark:bg-rose-950 dark:text-rose-100',
  };
  const label: Record<typeof scope, string> = {
    read: 'mcp:read',
    write: 'mcp:write',
    admin: 'mcp:admin',
  };
  return (
    <span
      className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${palette[scope]}`}
    >
      {label[scope]}
    </span>
  );
}

function AnnotationChip({
  children,
  tone = 'muted',
}: {
  children: React.ReactNode;
  tone?: 'muted' | 'warn';
}) {
  const palette =
    tone === 'warn'
      ? 'bg-red-50 text-red-900 dark:bg-red-950 dark:text-red-100 border-red-200 dark:border-red-900'
      : 'bg-muted text-muted-foreground border-border';
  return (
    <span
      className={`inline-flex items-center rounded-md border px-1.5 py-0.5 text-[10px] font-medium ${palette}`}
    >
      {children}
    </span>
  );
}

function ToolRow({ tool }: { tool: CatalogEntry }) {
  const a = tool.annotations;
  return (
    <li className="space-y-1 border-b border-border py-3 last:border-b-0">
      <div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
        <code className="text-sm font-medium">{tool.name}</code>
        <ScopeChip scope={tool.classification} />
        {a.readOnlyHint === true ? <AnnotationChip>read-only</AnnotationChip> : null}
        {a.destructiveHint === true ? (
          <AnnotationChip tone="warn">destructive</AnnotationChip>
        ) : null}
        {a.idempotentHint === true ? <AnnotationChip>idempotent</AnnotationChip> : null}
        {a.openWorldHint === true ? <AnnotationChip>open-world</AnnotationChip> : null}
      </div>
      {tool.title && tool.title !== tool.name ? (
        <p className="text-sm text-muted-foreground">
          <span className="font-medium text-foreground">{tool.title}</span>
          {tool.description ? <> — {tool.description}</> : null}
        </p>
      ) : tool.description ? (
        <p className="text-sm text-muted-foreground">{tool.description}</p>
      ) : null}
    </li>
  );
}

export default function McpDocsPage() {
  const grouped = groupedByDomain(typedCatalog.tools);
  const counts = typedCatalog.counts.byClassification;

  return (
    <div className="container max-w-3xl py-12 px-4 md:px-6">
      <div className="space-y-12">
        {/* ── 1. Hero ─────────────────────────────────────────────────── */}
        <header className="space-y-4">
          <p className="text-sm font-medium text-muted-foreground">PackRat MCP Connector</p>
          <h1 className="text-3xl font-bold tracking-tight md:text-4xl">
            Plan trips, build packs, check weather.
          </h1>
          <p className="text-lg text-muted-foreground">
            PackRat runs a Model Context Protocol server at{' '}
            <code className="text-sm">mcp.packratai.com</code>. Connect Claude or any MCP-capable
            client, sign in with your PackRat account, and use natural language to manage your gear,
            plan trips, check conditions, and post to your feed.
          </p>
        </header>

        {/* ── 2. Quickstart ──────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">Quickstart</h2>
          <p className="text-muted-foreground">
            PackRat is a <em>custom connector</em> in Claude.ai. The install:
          </p>
          <ol className="list-decimal space-y-3 pl-6 text-base">
            <li>
              In Claude.ai, open <strong>Settings → Connectors → Add custom connector</strong>.
            </li>
            <li>
              Paste the connector URL:{' '}
              <code className="rounded bg-muted px-1.5 py-0.5 text-sm">
                https://mcp.packratai.com/mcp
              </code>
            </li>
            <li>
              Claude redirects you to PackRat to sign in.{' '}
              <strong>
                You&apos;ll briefly see <code className="text-sm">api.packrat.world</code> in your
                browser address bar
              </strong>{' '}
              — that&apos;s our authorization server, hosted on a separate origin from the MCP
              endpoint for security (a standard OAuth 2.1 + PKCE split-host pattern). Sign in with
              your PackRat account, or create one at{' '}
              <Link href="/" className="text-primary hover:underline">
                packratai.com
              </Link>
              .
            </li>
            <li>
              Approve the requested scopes on the consent screen. Claude requests{' '}
              <code className="text-sm">mcp:read</code> and{' '}
              <code className="text-sm">mcp:write</code> by default. You can approve all, deny, or
              (in a future release) approve a subset. <code className="text-sm">mcp:admin</code> is
              only granted server-side based on your PackRat user role — non-admins never see it
              offered.
            </li>
            <li>
              You&apos;re returned to Claude.ai. The connector is now installed and the tool catalog
              is loaded.
            </li>
          </ol>
          <p className="text-sm text-muted-foreground">
            Tokens are short-lived (60 minutes) and refresh automatically. Revoke the connection at
            any time from your PackRat account settings or by emailing{' '}
            <Link href="mailto:hello@packratai.com" className="text-primary hover:underline">
              hello@packratai.com
            </Link>
            .
          </p>

          <details className="rounded-lg border border-border p-4 text-sm">
            <summary className="cursor-pointer font-medium">If your install fails…</summary>
            <div className="mt-3 space-y-3 text-muted-foreground">
              <p>
                The cross-origin install above depends on Claude.ai&apos;s OAuth discovery client
                correctly following the link from the MCP resource server to the authorization
                server. A handful of failure modes can show up:
              </p>
              <ul className="list-disc space-y-2 pl-5">
                <li>
                  <strong>
                    &ldquo;Could not connect&rdquo; or a CORS error in the browser console.
                  </strong>{' '}
                  The browser blocked Claude&apos;s probe of the authorization-server metadata.
                  Verify <code>api.packrat.world</code> is reachable from your network and not
                  filtered by a corporate proxy / VPN.
                </li>
                <li>
                  <strong>Sign-in succeeds but you bounce back to Claude with an error.</strong>{' '}
                  Some browser extensions strip the <code>Authorization</code> header on
                  cross-origin redirects. Try a fresh browser profile or disable third-party cookie
                  restrictions for <code>claude.ai</code> + <code>api.packrat.world</code>.
                </li>
                <li>
                  <strong>The consent screen shows the wrong client name.</strong> Claude.ai has
                  been pre-registered with the AS, so &ldquo;Claude&rdquo; should appear as the
                  requesting app. If you see <code>unknown</code> or a different name, the install
                  is pointed at the wrong URL — confirm you pasted{' '}
                  <code>https://mcp.packratai.com/mcp</code> exactly.
                </li>
                <li>
                  <strong>Tools work for ~60 minutes then stop.</strong> Refresh-token rotation
                  failed. Remove the connector in Claude.ai&apos;s settings and re-add it; if it
                  recurs, email{' '}
                  <Link href="mailto:hello@packratai.com" className="text-primary hover:underline">
                    hello@packratai.com
                  </Link>{' '}
                  with the timestamp and we&apos;ll check the AS logs.
                </li>
              </ul>
              <p>
                Operators: deeper failure modes (including the reverse-proxy fallback for
                cross-origin AS issues) are in{' '}
                <Link
                  href="https://github.com/PackRat-AI/PackRat/blob/main/docs/mcp/runbook.md"
                  className="text-primary hover:underline"
                >
                  docs/mcp/runbook.md § Post-refactor dev verification
                </Link>
                .
              </p>
            </div>
          </details>
        </section>

        {/* ── 3. Scopes ──────────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">OAuth scopes</h2>
          <p className="text-muted-foreground">
            PackRat advertises four coarse-grained scopes. Claude.ai requests{' '}
            <code className="text-sm">mcp:read</code> + <code className="text-sm">mcp:write</code>{' '}
            by default; <code className="text-sm">mcp:admin</code> is only granted to PackRat admin
            users and is the gate for destructive admin tooling.
          </p>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="border-b border-border text-left">
                  <th className="py-2 pr-4 font-semibold">Scope</th>
                  <th className="py-2 pr-4 font-semibold">Grants</th>
                </tr>
              </thead>
              <tbody>
                {typedCatalog.scopes.map((s) => (
                  <tr key={s.name} className="border-b border-border last:border-b-0">
                    <td className="py-2 pr-4 align-top">
                      <code className="text-sm">{s.name}</code>
                    </td>
                    <td className="py-2 pr-4 text-muted-foreground">{s.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* ── 4. Example prompts ─────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">Example prompts</h2>
          <p className="text-muted-foreground">
            Three prompts to try after connecting. Each exercises a different tool surface — a
            read-only query, a multi-tool plan, and a write that triggers an elicitation
            confirmation.
          </p>

          <article className="rounded-lg border border-border p-5 space-y-2">
            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Read-only · packs &amp; gear comparison
            </p>
            <blockquote className="border-l-2 border-primary pl-4 text-base italic">
              &ldquo;What&apos;s in my Big 3 right now? Suggest one swap to drop a pound.&rdquo;
            </blockquote>
            <p className="text-sm text-muted-foreground">
              Exercises <code className="text-xs">packrat_list_packs</code>,{' '}
              <code className="text-xs">packrat_list_pack_items</code>,{' '}
              <code className="text-xs">packrat_compare_gear_items</code>. Claude reads your current
              pack, finds the three heaviest items (shelter, sleep, pack), and proposes a single
              lighter substitute from the gear catalog.
            </p>
          </article>

          <article className="rounded-lg border border-border p-5 space-y-2">
            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Multi-tool plan · trip + weather + trail status + pack
            </p>
            <blockquote className="border-l-2 border-primary pl-4 text-base italic">
              &ldquo;Plan a 3-day trip to the Wind River Range next weekend; build the pack, check
              the weather, and flag any trail closures.&rdquo;
            </blockquote>
            <p className="text-sm text-muted-foreground">
              Exercises <code className="text-xs">packrat_search_trails</code>,{' '}
              <code className="text-xs">packrat_get_weather</code>,{' '}
              <code className="text-xs">packrat_list_my_trail_reports</code>,{' '}
              <code className="text-xs">packrat_create_trip</code>,{' '}
              <code className="text-xs">packrat_create_pack</code>. Claude composes a trip with the
              right gear for the forecast and surfaces any user-reported closures along the route.
            </p>
          </article>

          <article className="rounded-lg border border-border p-5 space-y-2">
            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Write with elicitation · TikTok URL → personal pack template
            </p>
            <blockquote className="border-l-2 border-primary pl-4 text-base italic">
              &ldquo;Find a TikTok ultralight loadout I saw at &lt;url&gt; and import it as a
              personal template.&rdquo;
            </blockquote>
            <p className="text-sm text-muted-foreground">
              Exercises <code className="text-xs">packrat_extract_url_content</code> and{' '}
              <code className="text-xs">packrat_generate_pack_template_from_url</code> (admin-only —
              for non-admin users, Claude falls back to{' '}
              <code className="text-xs">packrat_create_pack_template</code>). The tool triggers an
              MCP <strong>elicitation</strong> asking you to type{' '}
              <code className="text-xs">GENERATE</code> before importing — this is the
              user-confirmation pattern Anthropic&apos;s reviewers should see firing on
              high-blast-radius writes.
            </p>
          </article>
        </section>

        {/* ── 5. Tool catalog ────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">Tool catalog</h2>
          <p className="text-muted-foreground">
            The connector exposes <strong>{typedCatalog.totalTools} tools</strong> grouped into{' '}
            {grouped.length} domains: {counts.read} read-only, {counts.write} write, {counts.admin}{' '}
            admin. Each tool carries explicit MCP annotations (
            <code className="text-xs">readOnlyHint</code>,{' '}
            <code className="text-xs">destructiveHint</code>,{' '}
            <code className="text-xs">idempotentHint</code>,{' '}
            <code className="text-xs">openWorldHint</code>) so Claude can surface the right
            confirmation prompts.
          </p>
          <p className="text-sm text-muted-foreground">
            Catalog list views and resource lists are capped at 25 items to keep context lean; reach
            deeper with <code className="text-xs">packrat_search_gear_catalog</code> /{' '}
            <code className="text-xs">packrat_semantic_gear_search</code>.
          </p>
          <p className="text-xs text-muted-foreground">
            Catalog generated {new Date(typedCatalog.generatedAt).toISOString().slice(0, 10)} from
            the live registration code — see{' '}
            <code className="text-xs">packages/mcp/scripts/dump-catalog.ts</code>.
          </p>

          <div className="space-y-8">
            {grouped.map(([domain, tools]) => (
              <div key={domain}>
                <h3 className="mb-3 text-lg font-semibold tracking-tight">
                  {domain}{' '}
                  <span className="text-sm font-normal text-muted-foreground">
                    ({tools.length})
                  </span>
                </h3>
                <ul className="rounded-lg border border-border px-5">
                  {tools.map((t) => (
                    <ToolRow key={t.name} tool={t} />
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>

        {/* ── 6. Resources ───────────────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">Resources</h2>
          <p className="text-muted-foreground">
            PackRat publishes six MCP resources alongside the tool catalog. Templated resources
            carry list providers so MCP clients can enumerate the signed-in user&apos;s data via{' '}
            <code className="text-sm">resources/list</code> without guessing IDs.
          </p>
          <ul className="list-disc space-y-2 pl-6 text-sm">
            <li>
              <code>packrat://packs/&#123;packId&#125;</code> — a pack and its items. List provider
              returns the user&apos;s packs.
            </li>
            <li>
              <code>packrat://trips/&#123;tripId&#125;</code> — a trip&apos;s plan, destination, and
              dates. List provider returns the user&apos;s trips.
            </li>
            <li>
              <code>packrat://catalog/&#123;itemId&#125;</code> — a gear catalog item. List provider
              returns the first 25 items (use <code>packrat_search_gear_catalog</code> for deeper
              access).
            </li>
            <li>
              <code>packrat://catalog/categories</code> — the gear category tree.
            </li>
            <li>
              <code>packrat://search?q=&#123;query&#125;</code> — free-text query against the gear
              catalog.
            </li>
            <li>
              <code>packrat://glossary</code> — domain vocabulary (pack/trip/weight/trail/scope
              terms) as markdown. Reading this once at session start saves Claude tool calls
              re-learning terminology.
            </li>
          </ul>
        </section>

        {/* ── 7. Privacy + security ──────────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">Privacy &amp; security</h2>
          <ul className="list-disc space-y-2 pl-6 text-sm">
            <li>
              <strong>Tokens.</strong> OAuth access tokens are short-lived JWTs (60 minutes) signed
              by our authorization server on <code className="text-xs">api.packrat.world</code>.
              Refresh tokens last 30 days and rotate on every use. Token state is held on the
              authorization-server side; the MCP endpoint itself is stateless and verifies tokens
              against the AS&apos;s public JWKS.
            </li>
            <li>
              <strong>Passwords.</strong> Your PackRat password is never visible to the MCP client;
              sign-in happens entirely on <code className="text-xs">api.packrat.world</code> and
              only an opaque OAuth code is returned to Claude.
            </li>
            <li>
              <strong>Conversations.</strong> We do not log the conversation content you send to MCP
              clients — only the tool calls those clients make against PackRat.
            </li>
            <li>
              <strong>Audience-bound tokens.</strong> Per RFC 8707, every issued access token is
              bound to <code className="text-xs">https://mcp.packratai.com/mcp</code> so a stolen
              token can&apos;t be replayed against another service.
            </li>
          </ul>
          <p className="text-sm text-muted-foreground">
            Read the full{' '}
            <Link href="/privacy-policy#mcp" className="text-primary hover:underline">
              MCP section of the privacy policy
            </Link>
            , the{' '}
            <Link href="/terms-of-service" className="text-primary hover:underline">
              terms of service
            </Link>
            , or email{' '}
            <Link href="mailto:hello@packratai.com" className="text-primary hover:underline">
              hello@packratai.com
            </Link>{' '}
            for support.
          </p>
        </section>

        {/* ── 8. Reviewer test account ───────────────────────────────── */}
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold tracking-tight">Reviewer test account</h2>
          <p className="text-muted-foreground">
            Anthropic reviewers: test-account credentials are provided separately via the submission
            form. The packet doc (<code className="text-xs">docs/mcp/submission-packet.md</code> in
            the PackRat repo) lists what&apos;s populated in the account: a few packs with realistic
            items, a sample multi-day trip, and a public feed post. First-run instructions are in
            the same doc.
          </p>
          <p className="text-sm text-muted-foreground">
            We do not publish credentials on this page.
          </p>
        </section>

        {/* ── 9. Footer / pointers ───────────────────────────────────── */}
        <section className="space-y-2 border-t border-border pt-6 text-sm text-muted-foreground">
          <p>
            Developer docs:{' '}
            <Link
              href="https://github.com/PackRat-AI/PackRat/blob/main/packages/mcp/README.md"
              className="text-primary hover:underline"
            >
              packages/mcp/README.md
            </Link>
            .
          </p>
          <p>
            Implementation plan:{' '}
            <Link
              href="https://github.com/PackRat-AI/PackRat/blob/main/docs/plans/2026-05-22-001-feat-mcp-connector-store-readiness-plan.md"
              className="text-primary hover:underline"
            >
              docs/plans/2026-05-22-001-feat-mcp-connector-store-readiness-plan.md
            </Link>
            .
          </p>
          <p>
            Operator runbook:{' '}
            <Link
              href="https://github.com/PackRat-AI/PackRat/blob/main/docs/mcp/runbook.md"
              className="text-primary hover:underline"
            >
              docs/mcp/runbook.md
            </Link>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
