import type { LucideProps } from 'lucide-react';
import {
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Backpack,
  Bell,
  BookOpen,
  Brain,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  Clipboard,
  Clock,
  Cloud,
  Cog,
  Copy,
  Dumbbell,
  Eye,
  EyeOff,
  FileText,
  Flag,
  Folder,
  Globe,
  Image,
  Images,
  Info,
  Lightbulb,
  Link,
  List,
  Loader,
  type LucideIcon,
  Map as MapIcon,
  MapPin,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  Newspaper,
  Pencil,
  Phone,
  Plus,
  Puzzle,
  RefreshCw,
  Ruler,
  Search,
  Send,
  ShoppingCart,
  Smartphone,
  Soup,
  Star,
  Sun,
  Tag,
  Target,
  Trash,
  Trash2,
  Trophy,
  User,
  Users,
  Video,
  Wrench,
  X,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  'account-circle': User,
  'account-circle-outline': User,
  'account-multiple': Users,
  person: User,
  'person-outline': User,
  archive: Archive,
  'archive-arrow-up-outline': Archive,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-up': ArrowUp,
  check: Check,
  'check-circle': CheckCircle,
  'check-circle-outline': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-outline': Circle,
  close: X,
  'close-circle': X,
  minus: Minus,
  plus: Plus,
  restart: RefreshCw,
  send: Send,
  stop: Loader,
  'moon.stars': Moon,
  'sun.min': Sun,
  cloud: Cloud,
  'cloud-outline': Cloud,
  water: Cloud,
  'weather-rainy': Cloud,
  backpack: Backpack,
  'basket-outline': ShoppingCart,
  'cart-outline': ShoppingCart,
  bell: Bell,
  'bell-outline': Bell,
  'book-open-outline': BookOpen,
  brain: Brain,
  calendar: Calendar,
  'calendar-month': Calendar,
  camera: Camera,
  'camera-outline': Camera,
  'chart-pie': Trophy,
  cellphone: Smartphone,
  'cog-outline': Cog,
  'clipboard-outline': Clipboard,
  'clock-outline': Clock,
  'dots-horizontal': Loader,
  dumbbell: Dumbbell,
  exclamation: Info,
  eye: Eye,
  'eye-off': EyeOff,
  'file-copy': Copy,
  'file-document-multiple': FileText,
  'file-plus-outline': FileText,
  'file-search-outline': Search,
  flag: Flag,
  'flag-outline': Flag,
  folder: Folder,
  'format-list-bulleted': List,
  gear: Cog,
  image: Image,
  'image-multiple': Images,
  'image-outline': Image,
  'inbox-arrow-down': ArrowDown,
  information: Info,
  lightbulb: Lightbulb,
  link: Link,
  magnify: Search,
  'magnify-minus-outline': Search,
  map: MapIcon,
  'map-marker-outline': MapPin,
  'map-marker-radius-outline': MapPin,
  'map-outline': MapIcon,
  message: MessageCircle,
  'message-outline': MessageCircle,
  microphone: Mic,
  newspaper: Newspaper,
  'note-text-outline': FileText,
  'pencil-box-outline': Pencil,
  'phone-outline': Phone,
  puzzle: Puzzle,
  ruler: Ruler,
  settings: Cog,
  'silverware-fork-knife': Soup,
  'soccer-field': Globe,
  star: Star,
  'star-outline': Star,
  tag: Tag,
  'tag-outline': Tag,
  target: Target,
  'trash-can': Trash,
  'trash-can-outline': Trash2,
  'video-outline': Video,
  wrench: Wrench,
};

type IconProps = {
  name: string;
  size?: number;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
};

export function Icon({ name, size = 24, color, className, style }: IconProps) {
  const LucideComponent: LucideIcon = ICON_MAP[name] ?? Circle;
  const props: LucideProps = {
    size,
    className,
    style: color ? { color, ...style } : style,
  };
  return <LucideComponent {...props} />;
}
