import * as path from 'node:path';
import * as fs from 'fs-extra';
import { resolveEnvSource } from './env-source';

const isCI = process.env.CI === 'true';
if (isCI) {
  console.log('🏃 CI detected, skipping .env.local generation');
  process.exit(0);
}

console.log('🔥 Generating .env.local files');

const autogeneratedComment =
  '# This file is autogenerated. To make changes, modify the root level .env.local file and run bun install. You might need to directly run bun postinstall to trigger the env shim script. \n\n';
const outputName = '.env.local';

// Read the .env file.
//
// Resolved through env-source so a linked worktree — which never receives the
// gitignored .env.local from `git worktree add` — falls back to the main
// checkout's file instead of silently generating nothing.
const checkoutRoot = path.join(__dirname, '..', '..');
const envSource = resolveEnvSource(checkoutRoot);
if (!envSource.exists) {
  console.log(`🛑 No ${outputName} found at ${envSource.path}`);
  process.exit(0);
}
if (envSource.inherited) {
  console.log(`   Inheriting ${outputName} from the main checkout: ${envSource.path}`);
}
const envFileContent = fs.readFileSync(envSource.path, 'utf8');

// Guard: refuse to fan out a source that still carries .env.example placeholder
// values. Overwriting a working .dev.vars with `user:password@host:port` is a
// destructive no-win — the dev loses real credentials and gains nothing.
if (/postgres(?:ql)?:\/\/\w*:password@host/.test(envFileContent)) {
  console.log(
    `🛑 ${envSource.path} still contains .env.example placeholder values — refusing to\n` +
      '   overwrite generated env files. Fill in the real values first.',
  );
  process.exit(0);
}

/**
 * Generate Expo .env file content
 */
const expoOutputPath = path.join(checkoutRoot, 'apps', 'expo', outputName);
const RE_PUBLIC_PREFIX = /^PUBLIC_/;

const expoFileContent = envFileContent
  .split('\n')
  .flatMap((line) => {
    // Only keep EXPO_PUBLIC_ variables
    if (line.startsWith('PUBLIC_APP=')) {
      return 'EXPO_PUBLIC_APP=expo';
    } else if (line.startsWith('PUBLIC_')) {
      return line.replace(RE_PUBLIC_PREFIX, 'EXPO_PUBLIC_');
    } else if (line.startsWith('EXPO_PUBLIC_')) {
      return line;
    }
    return [];
  })
  .join('\n');
const expoNoTelemetry = 'EXPO_NO_TELEMETRY=true';
fs.writeFileSync(expoOutputPath, `${autogeneratedComment}\n${expoFileContent}\n${expoNoTelemetry}`);

/**
 * Generate API .dev.vars file content
 */
const apiOutputPath = path.join(checkoutRoot, 'packages', 'api', '.dev.vars');
const apiFileContent = envFileContent
  .split('\n')
  .map((line) => {
    if (line.startsWith('ENVIRONMENT=')) {
      // apiEnvSchema enforces z.enum(['development', 'production']) and
      // throws on parse failure — keep the canonical 'development' value
      // rather than the short 'dev' the script previously hardcoded.
      return 'ENVIRONMENT=development';
    }
    return line;
  })
  .join('\n');
fs.writeFileSync(apiOutputPath, `${autogeneratedComment}\n${apiFileContent}`);

/**
 * Generate .env.local for Next.js apps (admin, landing, guides).
 *
 * Rewrites PUBLIC_* → NEXT_PUBLIC_* so the same source var fans out to both
 * Expo (EXPO_PUBLIC_*) and Next.js (NEXT_PUBLIC_*). All other lines pass
 * through so server-side Next code (dev routes, API handlers) has access.
 * Only NEXT_PUBLIC_-prefixed vars are exposed to the client by Next.js.
 */
const nextJsApps = ['admin', 'landing', 'guides'] as const;
const nextFileContent = envFileContent
  .split('\n')
  .map((line) => {
    if (line.startsWith('PUBLIC_')) return line.replace(RE_PUBLIC_PREFIX, 'NEXT_PUBLIC_');
    return line;
  })
  .join('\n');

for (const app of nextJsApps) {
  const outputPath = path.join(checkoutRoot, 'apps', app, outputName);
  fs.writeFileSync(outputPath, `${autogeneratedComment}\n${nextFileContent}`);
}

console.log('✅ .env.local files generated successfully');
