# Not currently functional due to restructuring of project
version: "3"
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - 19000:19000
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
