# Creates a comment to show native preview build status
# Or finds the comment if it exists
# Exposes the comment id in env in either case
name: Find or create comment
description: 'Finds the comment of build status or create one. Outputs the comment id.'

inputs:
  github-token:
    description: 'Github token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Find or create comment
      uses: actions/github-script@v6
      with:
          github-token: ${{ inputs.github-token }}
          script: |
            const buildName = '${{ env.build-name }}';
            const commentMagicPrefix = '${{ env.comment-unique-magic-prefix }}';
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const existingComment = comments.data.find(comment => comment.body.startsWith(commentMagicPrefix));

            if (existingComment) {
              core.exportVariable('comment_id', existingComment.id)
            } else {
              const commentBody = `${commentMagicPrefix}\n🚀 ${buildName} build has started... Please wait for the results! 🕐`;
              const { data: { id: commentId } } = await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
              core.exportVariable('comment_id', commentId)
            }
