/**
 * Pre-build script: generates static Open Graph image PNGs for the guides site.
 *
 * Static exports (`output: 'export'`) cannot serve Next.js metadata-route images
 * (opengraph-image.tsx) correctly from a CDN — the generated .body/.meta files
 * are a Next.js-internal format, not plain PNG files.
 *
 * This script renders the same JSX used in opengraph-image.tsx via ImageResponse
 * and writes real .png files to public/ so Cloudflare Workers can serve them with
 * the correct Content-Type automatically.
 *
 * Outputs:
 *   public/og-image.png          — root / site-level OG image
 *   public/og/[slug].png         — per-post OG images
 *
 * IMPORTANT — build order matters:
 *   This script reads posts from `lib/content.ts`, which is auto-generated by
 *   `scripts/build-content.ts` from the MDX files in `content/posts/`. If you
 *   run this script BEFORE `build-content`, you will generate OG images for
 *   whatever post set was last committed to `lib/content.ts`, not the current
 *   set on disk. The `package.json` "build" script must therefore invoke
 *   `build-content` BEFORE `generate-og-images`. The guard below catches the
 *   order-inversion bug if it is ever reintroduced. See PR #2436 for context.
 *
 * Run: `bun run scripts/generate-og-images.ts`
 */

import fs from 'node:fs';
import path from 'node:path';
import { ImageResponse } from 'next/og';
import { createElement } from 'react';
import { getAllPosts } from '../lib/mdx-static';
import { getGuidesOgImageElement, getPostOgImageElement, OG_IMAGE_SIZE } from '../lib/og-image';

const PUBLIC_DIR = path.join(import.meta.dir, '..', 'public');
const OG_DIR = path.join(PUBLIC_DIR, 'og');
const POSTS_DIR = path.join(import.meta.dir, '..', 'content', 'posts');

/**
 * Detect the build-order-inversion bug from PR #2436: if there are many MDX
 * source files on disk but `lib/content.ts` only reports a small number of
 * posts, the caller almost certainly forgot to run `build-content` first.
 * Failing fast here is much cheaper than shipping a build with stale OG images.
 */
function assertContentIsFresh(postCount: number): void {
  let mdxFileCount = 0;
  try {
    mdxFileCount = fs.readdirSync(POSTS_DIR).filter((f) => f.endsWith('.mdx')).length;
  } catch {
    // If the posts directory is missing for some reason, skip the guard rather
    // than blocking generation entirely — the build will fail downstream.
    return;
  }

  // Threshold chosen to be well below the current ~500 posts but well above
  // the historical stale value (39). Adjust freely if the corpus shrinks.
  const STALE_POST_THRESHOLD = 50;
  const MIN_MDX_FILES_FOR_GUARD = 50;

  if (mdxFileCount > MIN_MDX_FILES_FOR_GUARD && postCount < STALE_POST_THRESHOLD) {
    throw new Error(
      `generate-og-images: only ${postCount} posts found in lib/content.ts but ` +
        `${mdxFileCount} MDX files exist in content/posts/. ` +
        `Did you forget to run \`bun run build-content\` first? ` +
        `The \`build\` script must run build-content BEFORE generate-og-images — see PR #2436.`,
    );
  }
}

async function renderToPng(element: ReturnType<typeof getGuidesOgImageElement>): Promise<Buffer> {
  const response = new ImageResponse(
    createElement(() => element),
    OG_IMAGE_SIZE,
  );
  return Buffer.from(await response.arrayBuffer());
}

async function generateOgImages(): Promise<void> {
  // Load posts and assert freshness BEFORE doing any expensive work so that
  // the build-order bug surfaces in seconds rather than minutes.
  const posts = getAllPosts();
  assertContentIsFresh(posts.length);

  fs.mkdirSync(OG_DIR, { recursive: true });

  // Root site image
  const rootBuffer = await renderToPng(getGuidesOgImageElement());
  const rootPath = path.join(PUBLIC_DIR, 'og-image.png');
  fs.writeFileSync(rootPath, rootBuffer);
  console.log(`✓ Generated ${path.relative(process.cwd(), rootPath)} (${rootBuffer.length} bytes)`);

  // Per-post images
  for (const post of posts) {
    const buffer = await renderToPng(
      getPostOgImageElement({
        title: post.title,
        description: post.description ?? '',
        categories: post.categories ?? [],
      }),
    );
    const outPath = path.join(OG_DIR, `${post.slug}.png`);
    fs.writeFileSync(outPath, buffer);
    console.log(`✓ Generated ${path.relative(process.cwd(), outPath)} (${buffer.length} bytes)`);
  }

  console.log(`\nDone — generated 1 root + ${posts.length} post OG images.`);
}

generateOgImages().catch((err) => {
  console.error('Failed to generate OG images:', err);
  process.exit(1);
});
