import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import { siteConfig } from '../lib/config';
import { getAllPosts } from '../lib/mdx-static';
import { guidesMetadata } from '../lib/metadata';

const APP_DIR = path.resolve(__dirname, '..');
const PUBLIC_DIR = path.join(APP_DIR, 'public');
const OG_DIR = path.join(PUBLIC_DIR, 'og');
const ROOT_OG_PATH = path.join(PUBLIC_DIR, 'og-image.png');

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

const EXPECTED_OG_URL = new URL('/og-image.png', siteConfig.url).toString();

/** Read a uint32 big-endian from a buffer at offset. */
function readUint32BE(buf: Buffer, offset: number): number {
  return buf.readUInt32BE(offset);
}

function assertValidPng(filePath: string): void {
  const buf = fs.readFileSync(filePath);
  expect(buf.subarray(0, 8), `${path.basename(filePath)} PNG signature`).toEqual(PNG_SIGNATURE);
  const width = readUint32BE(buf, 16);
  const height = readUint32BE(buf, 20);
  expect(width, `${path.basename(filePath)} width`).toBe(1200);
  expect(height, `${path.basename(filePath)} height`).toBe(630);
  expect(buf.length, `${path.basename(filePath)} size`).toBeGreaterThan(1024);
}

describe('guides OG image generation', () => {
  // Generating per-post PNGs takes ~30-60s for the full set;
  // default vitest hook timeout is 5s.
  beforeAll(() => {
    execSync('bun run scripts/generate-og-images.ts', {
      cwd: APP_DIR,
      stdio: 'inherit',
    });
  }, 180_000);

  it('generates public/og-image.png', () => {
    expect(fs.existsSync(ROOT_OG_PATH)).toBe(true);
  });

  it('root og-image.png is a valid 1200×630 PNG', () => {
    assertValidPng(ROOT_OG_PATH);
  });

  it('generates public/og/ directory', () => {
    expect(fs.existsSync(OG_DIR)).toBe(true);
  });

  it('generates a per-post PNG for every post', () => {
    const posts = getAllPosts();
    expect(posts.length).toBeGreaterThan(0);

    for (const post of posts) {
      const filePath = path.join(OG_DIR, `${post.slug}.png`);
      expect(fs.existsSync(filePath), `missing: og/${post.slug}.png`).toBe(true);
    }
  });

  it('every per-post PNG is a valid 1200×630 PNG', () => {
    const posts = getAllPosts();
    for (const post of posts) {
      assertValidPng(path.join(OG_DIR, `${post.slug}.png`));
    }
  });

  it('metadata.openGraph.images[0].url references the generated file', () => {
    const images = (guidesMetadata.openGraph as { images?: unknown })?.images;
    const first = Array.isArray(images) ? images[0] : images;
    const url = typeof first === 'string' ? first : (first as { url: string })?.url;
    // Derive the local path from the URL and assert the file exists.
    // This catches the class of bug where metadata points at /opengraph-image.png
    // (a Next.js internal route that static export does not expose as a real PNG)
    // instead of /og-image.png (the file written by scripts/generate-og-images.ts).
    const pathname = new URL(url).pathname;
    const filePath = path.resolve(APP_DIR, 'public', pathname.slice(1));
    expect(
      fs.existsSync(filePath),
      `og:image URL (${url}) → ${filePath} does not exist in public/. ` +
        'Ensure metadata points to a file generated by scripts/generate-og-images.ts.',
    ).toBe(true);
  });
});

describe('guides layout metadata', () => {
  it('openGraph.images[0].url is the absolute og-image.png URL', () => {
    const images = (guidesMetadata.openGraph as { images?: unknown })?.images;
    expect(images).toBeDefined();
    const first = Array.isArray(images) ? images[0] : images;
    const url = typeof first === 'string' ? first : (first as { url: string })?.url;
    expect(url).toBe(EXPECTED_OG_URL);
  });

  it('twitter.images[0] is the absolute og-image.png URL', () => {
    const images = (guidesMetadata.twitter as { images?: unknown })?.images;
    expect(images).toBeDefined();
    const first = Array.isArray(images) ? images[0] : images;
    const twitterUrl =
      typeof first === 'string' ? first : ((first as { url?: string })?.url ?? first);
    expect(twitterUrl).toBe(EXPECTED_OG_URL);
  });
});

describe('guides per-slug page metadata', () => {
  it('generateMetadata sets openGraph.images to /og/[slug].png', async () => {
    // Dynamically import to avoid top-level JSX issues in test runner
    const { generateMetadata } = await import('../app/guide/[slug]/page');
    const posts = getAllPosts();
    const post = posts[0];
    if (!post) throw new Error('No posts found');

    const meta = await generateMetadata({ params: Promise.resolve({ slug: post.slug }) });
    const images = (meta.openGraph as { images?: unknown })?.images;
    expect(images).toBeDefined();
    const first = Array.isArray(images) ? images[0] : images;
    const url = typeof first === 'string' ? first : (first as { url: string })?.url;
    expect(url).toBe(`/og/${post.slug}.png`);
  });

  it('generateMetadata sets twitter.images to /og/[slug].png', async () => {
    const { generateMetadata } = await import('../app/guide/[slug]/page');
    const posts = getAllPosts();
    const post = posts[0];
    if (!post) throw new Error('No posts found');

    const meta = await generateMetadata({ params: Promise.resolve({ slug: post.slug }) });
    const images = (meta.twitter as { images?: unknown })?.images;
    expect(images).toBeDefined();
    const first = Array.isArray(images) ? images[0] : images;
    expect(first).toBe(`/og/${post.slug}.png`);
  });

  it('generateMetadata per-post og:image file exists in public/og/', async () => {
    const { generateMetadata } = await import('../app/guide/[slug]/page');
    const posts = getAllPosts();
    const post = posts[0];
    if (!post) throw new Error('No posts found');

    const meta = await generateMetadata({ params: Promise.resolve({ slug: post.slug }) });
    const images = (meta.openGraph as { images?: unknown })?.images;
    const first = Array.isArray(images) ? images[0] : images;
    const url = typeof first === 'string' ? first : (first as { url: string })?.url;
    const filePath = path.resolve(APP_DIR, 'public', url.replace(/^\//, ''));
    expect(
      fs.existsSync(filePath),
      `per-post og:image points to ${url} but ${filePath} was not generated. ` +
        'Run scripts/generate-og-images.ts first.',
    ).toBe(true);
  });
});
