name: 'Setup Standard Environment'
description: 'Sets up the standard environment for building the app'

inputs:
  expo-token:
    description: 'Expo token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up JS Runtime Environment
      uses: ./.github/actions/setup-js-runtime

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.expo-token }}

    - name: Install dependencies
      uses: ./.github/actions/install-deps

    - name: Setup Java
      uses: ./.github/actions/setup-java