services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: packrat_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d packrat_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c log_statement=all
      -c log_duration=on
      -c max_connections=100

volumes:
  postgres_test_data: