name = "packrat-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
keep_vars = true
version_metadata = { binding = "CF_VERSION_METADATA" }

[vars]
ENVIRONMENT = "dev"
NEON_DATABASE_URL = "postgres://user:pass@localhost/db"
JWT_SECRET = "secret"
GOOGLE_CLIENT_ID="some-client-id"
OPENAI_API_KEY = "key"
EMAIL_PROVIDER = "resend"
RESEND_API_KEY = "key"
EMAIL_FROM = "test@example.com"
PASSWORD_RESET_SECRET = "secret"
WEATHER_API_KEY = "key"
OPENWEATHER_KEY = "key"
CLOUDFLARE_ACCOUNT_ID = "id"
R2_ACCESS_KEY_ID = "key"
R2_SECRET_ACCESS_KEY = "key"
PACKRAT_BUCKET_R2_BUCKET_NAME = "bucket"
PACKRAT_ITEMS_BUCKET_R2_BUCKET_NAME = "bucket"
PACKRAT_API_KEY = "key"
SENTRY_DSN = "dsn"
PACKRAT_GUIDES_RAG_NAME="packrat-guides-rag"
PACKRAT_GUIDES_WEBSITE_URL="url"

[[queues.producers]]
queue = "packrat-etl-queue"
binding = "ETL_QUEUE"

[[queues.consumers]]
queue = "packrat-etl-queue"
max_batch_size = 10
max_batch_timeout = 5

[ai]
binding = "AI" 