name: 'Print Wrangler Logs'
description: 'Prints Wrangler logs files if exist'
runs:
  using: 'composite'
  steps:
    - name: Print the last wrangler log file
      shell: bash
      run: |
        cat "$(ls -t /home/runner/.config/.wrangler/logs/* 2> /dev/null | head -n 1)" 2> /dev/null || true;
    - name: Delete wrangler log files after printing
      shell: bash
      run: |
        rm /home/runner/.config/.wrangler/logs/* || true;
