name: 'Generate Wrangler TOML'
description: 'Generates the wrangler.toml file for Cloudflare Workers'
inputs:
  GOOGLE_CLIENT_ID:
    description: 'Google Client ID'
    required: true
  GOOGLE_CLIENT_SECRET:
    description: 'Google Client Secret'
    required: true
  STMP_EMAIL:
    description: 'SMTP Email'
    required: true
  STMP_PASSWORD:
    description: 'SMTP Password'
    required: true
  JWT_SECRET:
    description: 'JWT Secret'
    required: true
  SEND_GRID_API_KEY:
    description: 'Send Grid API Key'
    required: true
  MAPBOX_ACCESS_TOKEN:
    description: 'Mapbox Access Token'
    required: true
  OPENWEATHER_KEY:
    description: 'OpenWeather Key'
    required: true
  VECTORIZE_API_KEY:
    description: 'Vectorize API Key'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare Account ID'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
  PREVIEW_DB_ID:
    description: 'Preview DB ID'
    required: true
  PRODUCTION_DB_ID:
    description: 'Production DB ID'
    required: true
  PREVIEW_GOOGLE_CLIENT_ID:
    description: 'Preview Google Client ID'
    required: true
  PREVIEW_GOOGLE_CLIENT_SECRET:
    description: 'Preview Google Client Secret'
    required: true
  PREVIEW_STMP_EMAIL:
    description: 'Preview SMTP Email'
    required: true
  PREVIEW_STMP_PASSWORD:
    description: 'Preview SMTP Password'
    required: true
  PREVIEW_JWT_SECRET:
    description: 'Preview JWT Secret'
    required: true
  PREVIEW_SEND_GRID_API_KEY:
    description: 'Preview Send Grid API Key'
    required: true
  PREVIEW_MAPBOX_ACCESS_TOKEN:
    description: 'Preview Mapbox Access Token'
    required: true
  PREVIEW_OPENWEATHER_KEY:
    description: 'Preview OpenWeather Key'
    required: true
  PREVIEW_VECTORIZE_API_KEY:
    description: 'Preview Vectorize API Key'
    required: true
  PREVIEW_CLOUDFLARE_ACCOUNT_ID:
    description: 'Preview Cloudflare Account ID'
    required: true
  PREVIEW_OPENAI_API_KEY:
    description: 'Preview OpenAI API Key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate wrangler.toml
      shell: bash
      working-directory: ${{ github.workspace }}/server
      run: |
        touch wrangler.toml .env.preview .env.production
        echo 'name = "packrat-api"' >> wrangler.toml
        echo 'main = "src/index.ts"' >> wrangler.toml
        echo 'compatibility_date = "2024-03-14"' >> wrangler.toml
        echo 'node_compat = true' >> wrangler.toml
        echo '[env.preview]' >> wrangler.toml
        echo '[[env.preview.d1_databases]]' >> wrangler.toml
        echo 'binding = "DB"' >> wrangler.toml
        echo 'database_name = "preview"' >> wrangler.toml
        echo 'database_id = "${{ inputs.PREVIEW_DB_ID }}"' >> wrangler.toml
        echo '[env.preview.ai]' >> wrangler.toml
        echo 'binding = "AI"' >> wrangler.toml
        echo '[[env.preview.vectorize]]' >> wrangler.toml
        echo 'binding = "VECTOR_INDEX"' >> wrangler.toml
        echo 'index_name = "vector-index-preview"' >> wrangler.toml
        echo '[env.preview.vars]' >> wrangler.toml
        echo 'NODE_ENV = "preview"' >> wrangler.toml
        sed -i '$a GOOGLE_CLIENT_ID = "${{ inputs.GOOGLE_CLIENT_ID }}"' wrangler.toml .env.preview .env.production
        sed -i '$a GOOGLE_CLIENT_SECRET = "${{ inputs.GOOGLE_CLIENT_SECRET }}"' wrangler.toml .env.preview .env.production
        sed -i '$a STMP_EMAIL = "${{ inputs.STMP_EMAIL }}"' wrangler.toml .env.preview .env.production
        sed -i '$a STMP_PASSWORD = "${{ inputs.STMP_PASSWORD }}"' wrangler.toml .env.preview .env.production
        sed -i '$a JWT_SECRET = "${{ inputs.JWT_SECRET }}"' wrangler.toml .env.preview .env.production
        sed -i '$a SEND_GRID_API_KEY = "${{ inputs.SEND_GRID_API_KEY }}"' wrangler.toml .env.preview .env.production
        sed -i '$a MAPBOX_ACCESS_TOKEN = "${{ inputs.MAPBOX_ACCESS_TOKEN }}"' wrangler.toml .env.preview .env.production
        sed -i '$a OSM_URI = "https://overpass-api.de/api/interpreter"' wrangler.toml .env.preview .env.production
        sed -i '$a WEATHER_URL = "https://api.openweathermap.org/data/2.5/forecast"' wrangler.toml .env.preview .env.production
        sed -i '$a OPENWEATHER_KEY = "${{ inputs.OPENWEATHER_KEY }}"' wrangler.toml .env.preview .env.production
        sed -i '$a VECTORIZE_API_KEY = "${{ inputs.VECTORIZE_API_KEY }}"' wrangler.toml .env.preview .env.production
        sed -i '$a CLOUDFLARE_ACCOUNT_ID = "${{ inputs.CLOUDFLARE_ACCOUNT_ID }}"' wrangler.toml .env.preview .env.production
        sed -i '$a OPENAI_API_KEY = "${{ inputs.OPENAI_API_KEY }}"' wrangler.toml .env.preview .env.production
        echo '[env.production]' >> wrangler.toml
        echo '[[env.production.d1_databases]]' >> wrangler.toml
        echo 'binding = "DB"' >> wrangler.toml
        echo 'database_name = "production"' >> wrangler.toml
        echo 'database_id = "${{ inputs.PRODUCTION_DB_ID }}"' >> wrangler.toml
        echo '[env.production.ai]' >> wrangler.toml
        echo 'binding = "AI"' >> wrangler.toml
        echo '[[env.production.vectorize]]' >> wrangler.toml
        echo 'binding = "VECTOR_INDEX"' >> wrangler.toml
        echo 'index_name = "vector-index"' >> wrangler.toml
        echo '[env.production.vars]' >> wrangler.toml
        echo 'NODE_ENV = "production"' >> wrangler.toml
        echo 'GOOGLE_CLIENT_ID = "${{ inputs.GOOGLE_CLIENT_ID }}"' >> wrangler.toml
        echo 'GOOGLE_CLIENT_SECRET = "${{ inputs.GOOGLE_CLIENT_SECRET }}"' >> wrangler.toml
        echo 'STMP_EMAIL = "${{ inputs.STMP_EMAIL }}"' >> wrangler.toml
        echo 'STMP_PASSWORD = "${{ inputs.STMP_PASSWORD }}"' >> wrangler.toml
        echo 'JWT_SECRET = "${{ inputs.JWT_SECRET }}"' >> wrangler.toml
        echo 'SEND_GRID_API_KEY = "${{ inputs.SEND_GRID_API_KEY }}"' >> wrangler.toml
        echo 'MAPBOX_ACCESS_TOKEN = "${{ inputs.MAPBOX_ACCESS_TOKEN }}"' >> wrangler.toml
        echo 'OSM_URI = "https://overpass-api.de/api/interpreter"' >> wrangler.toml
        echo 'WEATHER_URL = "https://api.openweathermap.org/data/2.5/forecast"' >> wrangler.toml
        echo 'OPENWEATHER_KEY = "${{ inputs.OPENWEATHER_KEY }}"' >> wrangler.toml
        echo 'VECTORIZE_API_KEY = "${{ inputs.VECTORIZE_API_KEY }}"' >> wrangler.toml
        echo 'CLOUDFLARE_ACCOUNT_ID = "${{ inputs.CLOUDFLARE_ACCOUNT_ID }}"' >> wrangler.toml
        echo 'OPENAI_API_KEY = "${{ inputs.OPENAI_API_KEY }}"' >> wrangler.toml
