name: Update build status
description: 'Updates build status comment with the build results'

inputs:
  github-token:
    description: 'Github token'
    required: true
  build-outcome:
    description: 'Build outcome'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Update build status
      uses: actions/github-script@v6
      with:
          github-token: ${{ inputs.github-token }}
          script: |
            const commentId = '${{ env.comment_id }}';
            const buildOutcome = '${{ inputs.build-outcome }}';
            const buildStatus = buildOutcome == 'success' ? 'completed' : 'failed';
            const buildName = '${{ env.build-name }}';
            const workflowUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            let commentBody = `${{ env.comment-unique-magic-prefix }}\n${buildName} build ${buildStatus}!`;

            if (buildOutcome == 'success') {
              commentBody += `\nYou can download the ${buildName} from the following link:\n${workflowUrl}#artifacts`;
            } else {
              commentBody += '\nPlease check the workflow logs for more details on the build failure.';
            }

            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentId,
              body: commentBody
            });