name: 'Set Environment Tokens'
description: 'Set environment variables for various tokens'
inputs:
  mapbox_token:
    description: 'Mapbox Downloads Token'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Set Mapbox Downloads Token
      if: inputs.mapbox_token != ''
      run: export MAPBOX_DOWNLOADS_TOKEN=${{ inputs.mapbox_token }}
      shell: bash