import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import { siteConfig } from '../config/site';
import { landingMetadata } from '../lib/metadata';

const APP_DIR = path.resolve(__dirname, '..');
const OG_IMAGE_PATH = path.resolve(APP_DIR, 'public/og-image.png');
const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

const EXPECTED_OG_URL = new URL('/og-image.png', siteConfig.url).toString();

/** Read a uint32 big-endian from a buffer at offset. */
function readUint32BE(buf: Buffer, offset: number): number {
  return buf.readUInt32BE(offset);
}

describe('landing OG image generation', () => {
  beforeAll(() => {
    execSync('bun run scripts/generate-og-images.ts', {
      cwd: APP_DIR,
      stdio: 'inherit',
    });
  });

  it('generates public/og-image.png', () => {
    expect(fs.existsSync(OG_IMAGE_PATH)).toBe(true);
  });

  it('output is a valid PNG file', () => {
    const buf = fs.readFileSync(OG_IMAGE_PATH);
    expect(buf.subarray(0, 8)).toEqual(PNG_SIGNATURE);
  });

  it('PNG has correct dimensions (1200 × 630)', () => {
    const buf = fs.readFileSync(OG_IMAGE_PATH);
    // IHDR chunk starts at byte 16; first 4 bytes = width, next 4 = height
    const width = readUint32BE(buf, 16);
    const height = readUint32BE(buf, 20);
    expect(width).toBe(1200);
    expect(height).toBe(630);
  });

  it('PNG is non-trivially sized (> 1 KB)', () => {
    const { size } = fs.statSync(OG_IMAGE_PATH);
    expect(size).toBeGreaterThan(1024);
  });

  it('metadata.openGraph.images[0].url references the generated file', () => {
    const images = (landingMetadata.openGraph as { images?: unknown })?.images;
    const first = Array.isArray(images) ? images[0] : images;
    const url = typeof first === 'string' ? first : (first as { url: string })?.url;
    // Derive the local path from the URL and assert the file exists.
    // This catches the class of bug where metadata points at /opengraph-image.png
    // (a Next.js internal route that static export does not expose as a real PNG)
    // instead of /og-image.png (the file written by scripts/generate-og-images.ts).
    const pathname = new URL(url).pathname;
    const filePath = path.resolve(APP_DIR, 'public', pathname.slice(1));
    expect(
      fs.existsSync(filePath),
      `og:image URL (${url}) → ${filePath} does not exist in public/. ` +
        'Ensure metadata points to a file generated by scripts/generate-og-images.ts.',
    ).toBe(true);
  });
});

describe('landing metadata', () => {
  it('openGraph.images[0].url is the absolute og-image.png URL', () => {
    const images = (landingMetadata.openGraph as { images?: unknown })?.images;
    expect(images).toBeDefined();
    const first = Array.isArray(images) ? images[0] : images;
    const url = typeof first === 'string' ? first : (first as { url: string })?.url;
    expect(url).toBe(EXPECTED_OG_URL);
  });

  it('twitter.images[0] is the absolute og-image.png URL', () => {
    const images = (landingMetadata.twitter as { images?: unknown })?.images;
    expect(images).toBeDefined();
    const first = Array.isArray(images) ? images[0] : images;
    const twitterUrl = typeof first === 'string' ? first : (first as { url?: string })?.url ?? first;
    expect(twitterUrl).toBe(EXPECTED_OG_URL);
  });
});
