name: 'Generate Wrangler TOML and Dotenv File'
description: 'Generates wrangler.toml and .env files for Cloudflare Workers'
inputs:
  APP_URL:
    description: 'The Application URL'
    required: true
  AWS_SIGN_ALGORITHM:
    description: 'The AWS sign algorithm'
    required: true
  BUCKET_ENDPOINT:
    description: 'The bucket endpoint'
    required: true
  BUCKET_NAME:
    description: 'The bucket name'
    required: true
  BUCKET_REGION:
    description: 'The bucket region'
    required: true
  BUCKET_SERVICE:
    description: 'The bucket service'
    required: true
  BUCKET_SESSION_TOKEN:
    description: 'The bucket session token'
    required: true
  environment:
    description: 'The current environment'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare Account ID'
    required: true
  DB_ID:
    description: 'The database ID'
    required: true
  GOOGLE_CLIENT_ID:
    description: 'Google Client ID'
    required: true
  STMP_EMAIL:
    description: 'SMTP Email'
    required: true
  VECTOR_INDEX_NAME:
    description: 'The vector index'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Generate wrangler.toml and .env
      shell: bash
      working-directory: ${{ github.workspace }}/server
      run: |
        echo 'NODE_ENV=development' > .env
        echo 'name = "packrat-api"' > wrangler.toml
        echo 'main = "src/index.ts"' >> wrangler.toml
        echo 'compatibility_date = "2024-03-14"' >> wrangler.toml
        echo 'node_compat = true' >> wrangler.toml
        echo '[env.${{ inputs.environment }}]' >> wrangler.toml
        echo '[[env.${{ inputs.environment }}.d1_databases]]' >> wrangler.toml
        echo 'binding = "DB"' >> wrangler.toml
        echo 'database_name = "${{ inputs.environment }}"' >> wrangler.toml
        echo 'database_id = "${{ inputs.DB_ID }}"' >> wrangler.toml
        echo 'migrations_dir = "${{ inputs.MIGRATIONS_PATH }}"' >> wrangler.toml
        echo '[[env.${{ inputs.environment }}.r2_buckets]]' >> wrangler.toml
        echo 'binding = "GEOJSON_BUCKET"' >> wrangler.toml
        echo 'bucket_name = "packrat-geojson-bucket-${{ inputs.environment }}"' >> wrangler.toml
        echo '[env.${{ inputs.environment }}.ai]' >> wrangler.toml
        echo 'binding = "AI"' >> wrangler.toml
        echo '[env.${{ inputs.environment }}.vars]' >> wrangler.toml
        echo 'APP_URL = "${{ inputs.APP_URL }}"' >> wrangler.toml
        echo 'AWS_SIGN_ALGORITHM = "${{ inputs.AWS_SIGN_ALGORITHM }}"' >> wrangler.toml
        echo 'BUCKET_ENDPOINT = "${{ inputs.BUCKET_ENDPOINT }}"' >> wrangler.toml
        echo 'BUCKET_NAME = "${{ inputs.BUCKET_NAME }}"' >> wrangler.toml
        echo 'BUCKET_REGION = "${{ inputs.BUCKET_REGION }}"' >> wrangler.toml
        echo 'BUCKET_SERVICE = "${{ inputs.BUCKET_SERVICE }}"' >> wrangler.toml
        echo 'BUCKET_SESSION_TOKEN = ${{ inputs.BUCKET_SESSION_TOKEN }}' >> wrangler.toml
        echo 'CLOUDFLARE_ACCOUNT_ID = "${{ inputs.CLOUDFLARE_ACCOUNT_ID }}"' >> wrangler.toml
        echo 'GOOGLE_CLIENT_ID = "${{ inputs.GOOGLE_CLIENT_ID }}"' >> wrangler.toml
        echo 'NODE_ENV = "${{ inputs.environment }}"' >> wrangler.toml
        echo 'OSM_URI = "https://overpass-api.de/api/interpreter"' >> wrangler.toml
        echo 'STMP_EMAIL = "${{ inputs.STMP_EMAIL }}"' >> wrangler.toml
        echo 'VECTOR_INDEX = "${{ inputs.VECTOR_INDEX_NAME }}"' >> wrangler.toml
        echo 'WEATHER_URL = "https://api.openweathermap.org/data/2.5/forecast"' >> wrangler.toml
