// Generated by wrangler types
// Cloudflare Workers environment bindings

import type { DurableObjectNamespace } from '@cloudflare/workers-types';
import type { TikTokContainer } from './src/index';

interface Env {
  TIKTOK_CONTAINER: DurableObjectNamespace<TikTokContainer>;
}
