// Generated by wrangler types
// Cloudflare Workers environment bindings

import type { DurableObjectNamespace } from '@cloudflare/workers-types';

/**
 * Environment bindings for the TikTok Service Worker
 */
export interface Env {
  /**
   * Durable Object binding for TikTokContainer
   * Used to manage container instances via Cloudflare Containers
   */
  TIKTOK_CONTAINER: DurableObjectNamespace;
}
