name: android-preview-build-local
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  update:
    name: EAS Android Build Local
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup environment variables
        run: |
          echo "MAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN" >> $GITHUB_ENV

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Prebuild
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          yarn run prebuild:expo

      - name: Create preview
        id: build
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          eas build --platform android --profile preview --local
          apk_path=$(find . -name '*.apk')
          echo "APK Path: ${apk_path}"
          echo "apk_path=${apk_path}" >> $GITHUB_ENV
        working-directory: apps/expo
        env:
          DEBUG: "true"
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: /home/runner/work/PackRat/PackRat/apps/expo/build-*.apk

      - name: Create Commit Comment
        if: github.event_name == 'push'
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Android APK build ${{ steps.build.outcome == 'success' && 'completed' || 'failed' }}!
            ${{ steps.build.outcome == 'success' && format('You can download the APK file from the following link:\nhttps://github.com/{0}/actions/runs/{1}#artifacts', github.repository, github.run_id) || 'Please check the workflow logs for more details on the build failure.' }}