name: 'Backend Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/backend.yml'
      - 'packages/validations/**'
      - 'packages/shared-types/**'
      - 'server/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup JS Runtime environment
        uses: ./.github/actions/setup-js-runtime

      - name: Generate wrangler.toml
        uses: ./.github/actions/setup-wrangler-toml
        with:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          STMP_EMAIL: ${{ secrets.STMP_EMAIL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PREVIEW_DB_ID: ${{ secrets.PREVIEW_DB_ID }}
          PRODUCTION_DB_ID: ${{ secrets.PRODUCTION_DB_ID }}
          PREVIEW_GOOGLE_CLIENT_ID: ${{ secrets.PREVIEW_GOOGLE_CLIENT_ID }}
          PREVIEW_STMP_EMAIL: ${{ secrets.PREVIEW_STMP_EMAIL }}
          PREVIEW_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.PREVIEW_CLOUDFLARE_ACCOUNT_ID }}

      - name: Migrate database
        uses: cloudflare/wrangler-action@v3.3.2
        with:
          wranglerVersion: '3.75.0'
          apiToken: skMQc0GKuojvn5rnaaAcabffiGTaypSKLnm-qVEs
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          workingDirectory: server
          preCommands: |
            echo '---Clear previous wrangler logs---'
            rm /home/runner/.config/.wrangler/logs/* || true
          command: d1 migrations apply production --remote --env production
          postCommands: |
            echo '---Print wrangler logs---'
            cat "$(ls -t /home/runner/.config/.wrangler/logs/* | head -n 1)" || true;
          packageManager: yarn
        env:
          NO_D1_WARNING: true
          CI: true
          WRANGLER_LOG: debug
          WRANGLER_LOG_SANITIZE: false

      - name: Print wrangler extra logs on failure 
        if: failure()
        run: | 
          cat "$(ls -t /home/runner/.config/.wrangler/logs/* | head -n 1)" || true;

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.3.2
        with:
          wranglerVersion: '3.75.0'
          apiToken: skMQc0GKuojvn5rnaaAcabffiGTaypSKLnm-qVEs
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          workingDirectory: server
          preCommands: | # INFO: We need to upload secret manually because the default secrets input of this action `cloudflare/wrangler-action@v3.3.2` use the `wrangler secret put` command to upload secrets but this command will do not work non-interactive context.
            echo '---Clear previous wrangler logs file---'
            rm /home/runner/.config/.wrangler/logs/* || true
            echo '---Generate and upload secrets---'
            echo '>> Generate secrets file'
            echo '{}' | jq '.GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"|.JWT_SECRET="${{ secrets.JWT_SECRET }}"|.MAPBOX_ACCESS_TOKEN="${{ secrets.MAPBOX_ACCESS_TOKEN }}"|.OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"|.OPENWEATHER_KEY="${{ secrets.OPENWEATHER_KEY }}"|.SEND_GRID_API_KEY="${{ secrets.SEND_GRID_API_KEY }}"|.STMP_PASSWORD="${{ secrets.STMP_PASSWORD }}"|.VECTORIZE_API_KEY="${{ secrets.VECTORIZE_API_KEY }}"|.X_AMZ_SECURITY_TOKEN="${{ secrets.X_AMZ_SECURITY_TOKEN }}"|.JWT_VERIFICATION_KEY="${{ secrets.JWT_SECRET }}"' > secrets.json
            echo '<< Secrets file generated'
            echo '>> Generated additional environment variables'
            echo 'APP_URL=${{ secrets.VITE_PUBLIC_APP_URL }}' > .env.preview
            echo '<< Additional environment variables generated'
            echo '>> Upload secrets'
            wrangler secret bulk --env production secrets.json
            echo '<< Secrets uploaded'
          command: deploy src/index.ts --env production
          packageManager: yarn
        env:
          CI: true
          NO_D1_WARNING: true
          WRANGLER_LOG: debug
          WRANGLER_LOG_SANITIZE: false

      - name: Print wrangler extra logs on failure 
        if: failure()
        run: | 
          cat "$(ls -t /home/runner/.config/.wrangler/logs/* | head -n 1)" || true;


