name: 'Backend Preview Deployment'

on:
  workflow_dispatch:
  push:
    branches:
      - andrew_testing
    paths:
      - '.github/workflows/backend-preview.yml'
      - 'packages/validations/**'
      - 'packages/shared-types/**'
      - 'server/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup JS Runtime environment
        uses: ./.github/actions/setup-js-runtime

      - name: Generate wrangler.toml
        uses: ./.github/actions/setup-wrangler-toml
        with:
          environment: preview
          APP_URL: ${{ secrets.VITE_PUBLIC_APP_URL }}
          AWS_SIGN_ALGORITHM: ${{ secrets.PREVIEW_AWS_SIGN_ALGORITHM }}
          BUCKET_ENDPOINT: ${{ secrets.PREVIEW_BUCKET_ENDPOINT }}
          BUCKET_NAME: ${{ secrets.PREVIEW_BUCKET_NAME }}
          BUCKET_REGION: ${{ secrets.PREVIEW_BUCKET_REGION }}
          BUCKET_SERVICE: ${{ secrets.PREVIEW_BUCKET_SERVICE }}
          BUCKET_SESSION_TOKEN: ${{ secrets.PREVIEW_BUCKET_SESSION_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          DB_ID: ${{ secrets.PREVIEW_DB_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.PREVIEW_GOOGLE_CLIENT_ID }}
          STMP_EMAIL: ${{ secrets.PREVIEW_STMP_EMAIL }}
          VECTOR_INDEX_NAME: ${{ secrets.PREVIEW_VECTOR_INDEX || 'vector-index-preview' }}

      - name: Migrate database
        uses: cloudflare/wrangler-action@v3.3.2
        with:
          wranglerVersion: '3.75.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          workingDirectory: server
          preCommands:  |
            echo '---Clear previous wrangler logs---'
            rm /home/runner/.config/.wrangler/logs/* || true
          command: d1 migrations apply preview --remote --env preview
          packageManager: yarn
        env:
          NO_D1_WARNING: true
          CI: true
          WRANGLER_LOG: debug
          WRANGLER_LOG_SANITIZE: false

      - name: Print wrangler extra logs on failure 
        if: failure()
        run: | 
          cat "$(ls -t /home/runner/.config/.wrangler/logs/* | head -n 1)" || true;

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.3.2
        with:
          wranglerVersion: '3.75.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID}}
          workingDirectory: server
          # INFO: We need to upload secret manually because the default secrets input of this action `cloudflare/wrangler-action@v3.3.2` use the `wrangler secret put` command to upload secrets but this command will do not work non-interactive context.
          preCommands: > 
            echo '---Clear previous wrangler logs file---' &&
            rm /home/runner/.config/.wrangler/logs/* || true &&
            echo '---Generate and upload secrets---' &&
            echo '>> Generate secrets file' &&
            echo '{}' | jq '
            .WORKERS_AI_API_KEY="${{ secrets.PREVIEW_WORKERS_AI_API_KEY }}" |
            .VECTORIZE_API_KEY="${{ secrets.PREVIEW_VECTORIZE_API_KEY }}" |
            .BUCKET_ACCESS_KEY_ID="${{ secrets.PREVIEW_BUCKET_ACCESS_KEY_ID }}" |
            .GOOGLE_CLIENT_SECRET="${{ secrets.PREVIEW_GOOGLE_CLIENT_SECRET }}" |
            .JWT_SECRET="${{ secrets.PREVIEW_JWT_SECRET }}" |
            .MAPBOX_ACCESS_TOKEN="${{ secrets.PREVIEW_MAPBOX_ACCESS_TOKEN }}" |
            .OPENAI_API_KEY="${{ secrets.PREVIEW_OPENAI_API_KEY }}" |
            .OPENWEATHER_KEY="${{ secrets.PREVIEW_OPENWEATHER_KEY }}" |
            .SEND_GRID_API_KEY="${{ secrets.PREVIEW_SEND_GRID_API_KEY }}" |
            .STMP_PASSWORD="${{ secrets.PREVIEW_STMP_PASSWORD }}" |
            .VECTORIZE_API_KEY="${{ secrets.PREVIEW_VECTORIZE_API_KEY }}" |
            .X_AMZ_SECURITY_TOKEN="${{ secrets.PREVIEW_X_AMZ_SECURITY_TOKEN }}" |
            .JWT_VERIFICATION_KEY="${{ secrets.PREVIEW_JWT_SECRET }}"
            ' > secrets.json &&
            echo '<< Secrets file generated' &&
            echo '>> Upload secrets' &&
            yarn wrangler secret bulk --env preview secrets.json &&
            echo '<< Secrets uploaded'
          command: deploy src/index.ts --env preview
          packageManager: yarn
        env:
          CI: true
          NO_D1_WARNING: true
          WRANGLER_LOG: debug
          WRANGLER_LOG_SANITIZE: false

      - name: Print wrangler extra logs on failure 
        if: failure()
        run: | 
          cat "$(ls -t /home/runner/.config/.wrangler/logs/* | head -n 1)" || true;

