name: Biome Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run Biome check
        run: bun biome check
