name: android-build-apk-gradlew

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android-gradlew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Standard Environment
        uses: ./.github/actions/setup-standard-environment
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Prebuild
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          yarn run prebuild:expo

      - name: Build Android Release
        run: |
          cd apps/expo/android && ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
