name: Workflow Status Commenter

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_run:
    workflows:
      [
        'android-preview-build-local',
        'Run Tests',
        'Node.js CI',
        'Node.js CI for Development Environment',
        'EAS Local Build',
      ]
    types: [completed]

jobs:
  comment-workflow-status:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine branch name
        id: get-branch
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Fetch workflow runs
        id: fetch-workflows
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = process.env.BRANCH_NAME;
            const workflows = [
              'android-preview-build-local',
              'Run Tests',
              'Node.js CI',
              'Node.js CI for Development Environment',
              'EAS Local Build',
            ];

            const response = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: branch,
              status: 'completed',
              per_page: 100 // Adjust this as needed
            });

            const filteredRuns = response.data.workflow_runs.filter(run => workflows.includes(run.name));
            return JSON.stringify(filteredRuns);

      - name: Create Comment Body
        id: create-table
        env:
          WORKFLOW_RESULTS: ${{ steps.fetch-workflows.outputs.result }}
        run: |
          const workflows = JSON.parse('${{ env.WORKFLOW_RESULTS }}');
          let commentBody = "## Workflow Status\n| Workflow | Status | Details |\n|----------|--------|---------|\n";

          workflows.forEach(workflow => {
            let emoji;
            switch (workflow.conclusion) {
              case 'success':
                emoji = '✅';
                break;
              case 'failure':
                emoji = '❌';
                break;
              case 'cancelled':
                emoji = '🚫';
                break;
              case null:
                emoji = '🔄';
                break;
              default:
                emoji = '⏺️';
            }

            commentBody += `| ${workflow.name} | ${emoji} ${workflow.conclusion || 'Loading...'} | [Logs](${workflow.html_url}) |\n`;
          });

          echo "::set-output name=body::${commentBody}"

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.create-table.outputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on Push
        if: github.event_name == 'push' || github.event_name == 'workflow_run'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.workflow_run.id }}
          body: ${{ steps.create-table.outputs.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
