name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev
      - andrew_testing
      - release/*
  pull_request:
    branches:
      - master
      - dev
      - andrew_testing

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t packrat-app -f Dockerfile.prod .