name: EAS Build Manual

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform (android or ios)'
        required: true
        default: 'android'
        type: choice
        options:
          - android
          - ios
      build-type:
        description: 'Build type (preview or local)'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - local

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  update:
    name: EAS ${{ github.event.inputs.platform }} ${{ github.event.inputs.build-type }} Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Setup EAS
        uses: ./.github/actions/setup-eas
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
          node-version: '20.x'

      - name: Create build
        uses: expo/expo-github-action/preview@v8
        with:
          working-directory: apps/expo
          command: |
            eas build --platform ${{ github.event.inputs.platform }} --profile preview \
            ${{ github.event.inputs.build-type == 'local' && '--local' || '' }}