# Native production pipeline
# Builds on EAS Cloud with auto submission
name: EAS Build & Submit

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/app/**'
      - 'apps/expo/**'
      - 'packages/ui/**'
      - 'packages/config/**'
      - 'packages/crosspath/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup EAS
        uses: ./.github/actions/setup-eas
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Inject `ascAppId` into `eas.json`
        shell: bash
        working-directory: ${{ github.workspace }}/apps/expo
        run: echo "$(jq '.submit.production.ios.ascAppId = "${{ secrets.ASC_APP_ID }}"' eas.json)" > eas.json

      - name: Get Build Version
        working-directory: ./apps/expo
        shell: bash
        run: |
          MAJOR_MINOR_VERSIONS=$(jq -r '.expo.version' app.json)
          PATCH_VERSION=${{ github.run_number }}
          APP_VERSION="${MAJOR_MINOR_VERSIONS%.*}.$PATCH_VERSION"
          jq --arg version "$APP_VERSION" '.expo.version = $version' app.json > app.json.temp && mv app.json.temp app.json

      - name: Build on EAS
        working-directory: ./apps/expo
        run: eas build --platform all --profile production --non-interactive --no-wait --auto-submit
