name: EAS Local Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env: # Define a shared environment variable for android and ios build.
  MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
  EXPO_PUBLIC_CLIENT_URL: ${{ secrets.EXPO_PUBLIC_CLIENT_URL }}
  EXPO_PUBLIC_API_URL: ${{ secrets.EXPO_PUBLIC_API_URL }}
  EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN: ${{ secrets.EXPO_PUBLIC_MAPBOX_ACCESS_TOKEN }}

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Standard Environment
        uses: ./.github/actions/setup-standard-environment
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Local Build for Android
        working-directory: ./apps/expo
        run: |
          eas build --profile preview --platform android --local --non-interactive
        env:
          EXPO_PUBLIC_ANDROID_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_ANDROID_CLIENT_ID }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: /home/runner/work/PackRat/PackRat/apps/expo/build-*.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Standard Environment
        uses: ./.github/actions/setup-standard-environment
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      # - name: Setup Xcode
      #   uses: maxim-lobanov/setup-xcode@v1
      #   with:
      #     xcode-version: latest-stable

      - name: Run Local Build for iOS
        working-directory: ./apps/expo
        run: |
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          eas build --profile preview --platform ios --local --non-interactive
        env:
          EXPO_PUBLIC_IOS_CLIENT_ID: ${{ secrets.EXPO_PUBLIC_IOS_CLIENT_ID }}

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: /home/runner/work/PackRat/PackRat/apps/expo/build-*.ipa
