name: iOS App Release Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Setup environment variables
        run: |
          echo "MAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN" >> $GITHUB_ENV

      - name: Prebuild
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          yarn run prebuild:expo

      - name: Build iOS app
        run: |
          echo "Using Mapbox Token: $MAPBOX_DOWNLOADS_TOKEN"
          export MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          eas build --platform ios --profile preview --local --non-interactive --output ${{ github.workspace }}/app-release.ipa
        env:
          DEBUG: 'true'
        continue-on-error: true

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.ipa

      - name: Create Commit Comment
        if: github.event_name == 'push'
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            iOS app build ${{ steps.build.outcome == 'success' && 'completed' || 'failed' }}!
            ${{ steps.build.outcome == 'success' && format('You can download the IPA file from the following link:\nhttps://github.com/{0}/actions/runs/{1}#artifacts', github.repository, github.run_id) || 'Please check the workflow logs for more details on the build failure.' }}
