name: Merge main into development
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  merge-main-into-development:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-main-to-development
          base: development
          title: "chore: sync main to development"
          body: |
            Automated PR to sync changes from `main` to `development`.
            
            This PR is created automatically when changes are pushed to `main`.
          labels: automated
          delete-branch: true