name: Node.js CI for Development Environment

on:
  push:
    branches: [ "**" ] # adjust this to the branches you want to run CI on
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Operating systems
        node-version: [18.x, 20.x, 21.x] # Node.js versions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Debug Information
      run: |
        yarn -v
        ls .yarn/releases
        cat .yarnrc.yml
        cat yarn.lock

    - name: ⚙️ Enable Corepack
      run: |
        corepack enable
        echo "corepack enabled"

    - name: Set Yarn Version to Berry
      run: yarn set version berry

    #   run: yarn policies set-version

    - name: Install dependencies
      uses: ./.github/actions/install-deps

    - name: Debug more
      run: |
        yarn -v
        yarn info packrat-world@workspace:.
        yarn workspaces list --json

    - name: Run setup
      run: |
        yarn -v
        which yarn
        yarn set version stable
        yarn install

# cp client/.env.example client/.env
# cp client/app.json.example client/app.json
# cp server/.env.example server/.env

# yarn setup

    # - name: Clean Cache and Reinstall
    #   run: |
    #     yarn cache clean
    #     yarn install --immutable

    - name: Start Server in Background
      run: |
        cd server
        yarn start &

    - name: Start Expo in Background
      run: |
        cd apps/expo
        yarn web &

    - name: Wait for a while
      run: sleep 120  # wait for some time to let the server start

    - name: Kill Background Jobs (Unix)
      if: matrix.os != 'windows-latest'
      run: kill $(jobs -p) || true

    - name: Kill Background Jobs (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Get-Job | Stop-Job
        Get-Job | Remove-Job

