name: Refresh Lockfile

on:
  issue_comment:
    types: [created]

jobs:
  refresh-lockfile:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/refresh-lockfile')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup Standard Environment
        uses: ./.github/actions/setup-standard-environment
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: Refresh lockfile
        run: yarn regen

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add yarn.lock
          git commit -m 'Refresh lockfile'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
