name: Tauri Build and Publish

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-tauri:
    name: Tauri Build and Publish
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            arch: 'arm64'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            arch: 'x64'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check for GITHUB_TOKEN
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "You must provide a GITHUB_TOKEN secret for this repository."
            exit 1
          fi
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Add macOS-specific Rust targets
        if: matrix.platform == 'macos-latest'
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: yarn install

      - name: Build and Publish Tauri App
        uses: tauri-apps/tauri-action@v0.5.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'App v${{ github.ref_name }}'
          releaseBody: 'See the assets to download this version and install.'
          draft: false
          prerelease: false
          args: ${{ matrix.args }}

      - name: Upload Tauri Artifacts (RPM and DEB)
        uses: actions/upload-artifact@v4
        with:
          name: tauri-artifacts-${{ matrix.platform }}
          path: |
            apps/tauri/src-tauri/target/release/bundle/deb/**
            apps/tauri/src-tauri/target/release/bundle/rpm/**
