#!/usr/bin/env bun
// `bun devenv` — ephemeral, per-agent development environments.
//
//   bun devenv up            Neon branch off `development` + wrangler dev on a free port
//   bun devenv down          Stop the API and delete the Neon branch
//   bun devenv list          Every live environment on this machine
//   bun devenv url           Print DATABASE_URL / API URL for the current environment
//   bun devenv prune         Delete environments whose worktree or branch is gone
//
// The Neon branch is copy-on-write off `development`, so it is created in a
// couple of seconds and carries that branch's seed data with no copy cost.

import { execFileSync, spawn } from 'node:child_process';
import { existsSync, openSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import {
  allocatePort,
  BRANCH_PREFIX,
  DEFAULT_PARENT_BRANCH,
  defaultName,
  REPO_ROOT,
  requireNeonApiKey,
  requireNeonProjectId,
  slugify,
} from './config';
import { NeonClient } from './neon';
import {
  type DevEnvRecord,
  deleteRecord,
  isAlive,
  listRecords,
  readRecord,
  STATE_DIR,
  saveRecord,
} from './state';

const API_DIR = resolve(REPO_ROOT, 'packages', 'api');

/** The NEON_DATABASE_URL line in .dev.vars, replaced per environment. */
const RE_NEON_URL_LINE = /^\s*NEON_DATABASE_URL\s*=/;
/** Password segment of a Postgres URL, masked before printing. */
const RE_URL_PASSWORD = /:[^:@]+@/;

interface Args {
  command: string;
  name?: string;
  parent: string;
  detach: boolean;
  keepBranch: boolean;
  json: boolean;
}

function parseArgs(argv: string[]): Args {
  const [command = 'help', ...rest] = argv;
  const args: Args = {
    command,
    parent: DEFAULT_PARENT_BRANCH,
    detach: false,
    keepBranch: false,
    json: false,
  };
  for (let i = 0; i < rest.length; i++) {
    const arg = rest[i];
    if (!arg) continue;
    if (arg === '--name') args.name = slugify(rest[++i] ?? '');
    else if (arg === '--parent') args.parent = rest[++i] ?? DEFAULT_PARENT_BRANCH;
    else if (arg === '--detach' || arg === '-d') args.detach = true;
    else if (arg === '--keep-branch') args.keepBranch = true;
    else if (arg === '--json') args.json = true;
    else if (!arg.startsWith('-') && !args.name) args.name = slugify(arg);
  }
  return args;
}

function client(): NeonClient {
  return new NeonClient(requireNeonApiKey(), requireNeonProjectId());
}

/**
 * Write the environment's own `.dev.vars.devenv`, derived from the committed
 * `.dev.vars` with NEON_DATABASE_URL swapped for the branch URL. The base file
 * is left untouched so an environment never disturbs a plain `bun api`.
 */
function writeDevVars(name: string, databaseUrl: string): string {
  const base = resolve(API_DIR, '.dev.vars');
  if (!existsSync(base)) {
    throw new Error(`${base} not found. Run \`bun install\` to generate it from .env.local.`);
  }
  const target = resolve(API_DIR, `.dev.vars.devenv-${name}`);
  const body = readFileSync(base, 'utf8')
    .split('\n')
    .filter((line) => !RE_NEON_URL_LINE.test(line))
    .join('\n');
  writeFileSync(
    target,
    `# Autogenerated by \`bun devenv up ${name}\` — do not edit, do not commit.\n` +
      `${body}\nNEON_DATABASE_URL=${databaseUrl}\n`,
  );
  return target;
}

async function migrate(databaseUrl: string): Promise<void> {
  // A branch off `development` already carries that branch's schema; this only
  // applies migrations the current checkout adds on top.
  const proc = spawn('bun', ['run', 'db:migrate'], {
    cwd: API_DIR,
    env: { ...process.env, NEON_DATABASE_URL: databaseUrl, DATABASE_URL: databaseUrl },
    stdio: 'inherit',
  });
  const code: number = await new Promise((done) => proc.on('exit', (c) => done(c ?? 1)));
  if (code !== 0) throw new Error(`db:migrate exited with ${code}`);
}

/** Where a detached environment's API output is written. */
export function logPath(name: string): string {
  return join(STATE_DIR, `${name}.log`);
}

function startApi(opts: { record: DevEnvRecord; varsFile: string; detach: boolean }) {
  const { record, varsFile, detach } = opts;
  const logFd = detach ? openSync(logPath(record.name), 'a') : undefined;
  const proc = spawn(
    'bunx',
    [
      'wrangler',
      'dev',
      '-e=dev',
      '--port',
      String(record.port),
      '--env-file',
      varsFile,
      // The container binding makes wrangler require a running Docker daemon,
      // which a dev environment for API work does not need. Opt in with
      // DEVENV_CONTAINERS=1 when actually exercising container routes.
      ...(process.env.DEVENV_CONTAINERS === '1' ? [] : ['--enable-containers=false']),
    ],
    {
      cwd: API_DIR,
      env: { ...process.env, PORT: String(record.port) },
      // Detached output goes to a log rather than /dev/null: a backgrounded API
      // that dies on startup would otherwise fail completely silently, leaving
      // a record that claims 'running' with nothing behind it.
      stdio: detach ? ['ignore', logFd, logFd] : 'inherit',
      detached: detach,
    },
  );
  if (detach) proc.unref();
  return proc;
}

async function up(args: Args): Promise<void> {
  // Validate + regenerate env before provisioning anything on Neon, so a
  // misconfigured checkout fails in a second rather than after creating a
  // branch it cannot use.
  execFileSync('bun', ['run', resolve(REPO_ROOT, '.github', 'scripts', 'env-check.ts')], {
    cwd: REPO_ROOT,
    stdio: 'inherit',
  });

  const name = args.name ?? defaultName(process.cwd());
  const existing = readRecord(name);
  if (existing) {
    console.error(
      `Environment "${name}" already exists (port ${existing.port}).\n` +
        `  Reuse it:  ${existing.databaseUrl.replace(RE_URL_PASSWORD, ':***@')}\n` +
        '  Replace:   bun devenv down ' +
        name,
    );
    process.exit(1);
  }

  const neon = client();
  const branchName = `${BRANCH_PREFIX}${name}`;
  const parent = await neon.findBranchByName(args.parent);
  if (!parent) throw new Error(`Parent Neon branch "${args.parent}" not found.`);

  console.log(`→ Branching Neon "${args.parent}" → "${branchName}"`);
  const created = await neon.createBranch({ name: branchName, parentId: parent.id });

  // From here on the branch exists remotely. Anything that throws before the
  // record is persisted would strand it — invisible to `down` and `prune`,
  // which both work off the local registry — so roll back explicitly.
  let databaseUrl: string;
  try {
    const database = created.databases[0];
    if (!database) throw new Error('Neon created the branch but reported no database on it.');
    // Pooled: the Worker opens a connection per request, so pgbouncer is what
    // keeps a branch from exhausting its connection limit under load.
    databaseUrl = await neon.connectionUri({
      branchId: created.branch.id,
      databaseName: database.name,
      roleName: database.owner_name,
      pooled: true,
    });
  } catch (error) {
    await neon.deleteBranch(created.branch.id).catch(() => {
      console.warn(`  Could not remove the partial Neon branch ${branchName} — delete it by hand.`);
    });
    throw error;
  }

  const port = await allocatePort();
  const record: DevEnvRecord = {
    name,
    neonBranchId: created.branch.id,
    neonBranchName: branchName,
    databaseUrl,
    port,
    worktree: process.cwd(),
    createdAt: new Date().toISOString(),
  };
  // Persist before migrating so a failed migration still leaves a branch that
  // `devenv down` can clean up rather than an orphan on Neon.
  saveRecord(record);

  const varsFile = writeDevVars(name, databaseUrl);

  // Regenerate the client env files pointed at this environment's own port, so
  // Expo and the Next apps in this worktree talk to this API rather than the
  // shared default port another agent may own.
  console.log(`→ Pointing clients at http://localhost:${port}`);
  execFileSync('bun', ['run', resolve(REPO_ROOT, '.github', 'scripts', 'env.ts')], {
    cwd: REPO_ROOT,
    env: { ...process.env, DEVENV_API_URL: `http://localhost:${port}` },
    stdio: 'inherit',
  });

  console.log('→ Applying migrations');
  await migrate(databaseUrl);

  console.log(`\n✓ ${name}  ·  API http://localhost:${port}  ·  Neon ${branchName}`);
  console.log(`  Tear down: bun devenv down ${name}\n`);

  const proc = startApi({ record, varsFile, detach: args.detach });
  if (args.detach) {
    saveRecord({ ...record, apiPid: proc.pid });
    console.log(`  API log: ${logPath(name)}`);
    return;
  }
  saveRecord({ ...record, apiPid: proc.pid });
  const stop = () => proc.kill('SIGTERM');
  process.on('SIGINT', stop);
  process.on('SIGTERM', stop);
  await new Promise((done) => proc.on('exit', done));
}

async function down(args: Args): Promise<void> {
  const name = args.name ?? defaultName(process.cwd());
  const record = readRecord(name);
  if (!record) {
    console.error(`No environment named "${name}". Run: bun devenv list`);
    process.exit(1);
  }

  if (isAlive(record.apiPid)) {
    try {
      process.kill(record.apiPid as number, 'SIGTERM');
    } catch {
      // Already gone between the check and the signal — nothing to stop.
    }
  }

  if (!args.keepBranch) {
    try {
      await client().deleteBranch(record.neonBranchId);
    } catch (error) {
      // A branch deleted by hand in the console must not strand the record.
      console.warn(`  Neon branch delete failed (removing the record anyway): ${String(error)}`);
    }
  }

  const varsFile = resolve(API_DIR, `.dev.vars.devenv-${name}`);
  if (existsSync(varsFile)) rmSync(varsFile);
  deleteRecord(name);

  // Regenerate the client env from the shared source, so the worktree's
  // generated files stop pointing at a port that no longer serves anything.
  execFileSync('bun', ['run', resolve(REPO_ROOT, '.github', 'scripts', 'env.ts')], {
    cwd: REPO_ROOT,
    stdio: 'ignore',
  });

  console.log(`✓ Removed ${name}`);
}

function list(args: Args): void {
  const records = listRecords();
  if (args.json) {
    console.log(JSON.stringify(records, null, 2));
    return;
  }
  if (records.length === 0) {
    console.log('No dev environments. Create one: bun devenv up');
    return;
  }
  for (const r of records) {
    const state = isAlive(r.apiPid) ? 'running' : 'stopped';
    console.log(`${r.name.padEnd(28)} :${r.port}  ${state.padEnd(8)} ${r.worktree}`);
  }
}

function url(args: Args): void {
  const name = args.name ?? defaultName(process.cwd());
  const record = readRecord(name);
  if (!record) {
    console.error(`No environment named "${name}". Run: bun devenv list`);
    process.exit(1);
  }
  if (args.json) {
    console.log(JSON.stringify(record, null, 2));
    return;
  }
  console.log(`NEON_DATABASE_URL=${record.databaseUrl}`);
  console.log(`PUBLIC_API_URL=http://localhost:${record.port}`);
  console.log(`EXPO_PUBLIC_API_URL=http://localhost:${record.port}`);
  console.log(`NEXT_PUBLIC_API_URL=http://localhost:${record.port}`);
}

/**
 * Drop environments whose worktree no longer exists — the common leak when an
 * agent's worktree is removed without a `devenv down`.
 */
async function prune(): Promise<void> {
  const records = listRecords();
  const stale = records.filter((r) => !existsSync(r.worktree));
  for (const record of stale) {
    console.log(`→ Pruning ${record.name} (worktree gone: ${record.worktree})`);
    await down({ ...parseArgs([]), command: 'down', name: record.name });
  }

  // Also sweep `devenv/` branches with no local record at all. An interrupted
  // `up`, or a record deleted by hand, leaves a branch that nothing else knows
  // to clean up — it would otherwise sit on the Neon project indefinitely.
  const known = new Set(listRecords().map((r) => r.neonBranchName));
  const neon = client();
  const orphans = (await neon.listBranches()).filter(
    (b) => b.name.startsWith(BRANCH_PREFIX) && !known.has(b.name),
  );
  for (const branch of orphans) {
    console.log(`→ Deleting orphaned Neon branch ${branch.name}`);
    await neon.deleteBranch(branch.id);
  }

  if (stale.length === 0 && orphans.length === 0) console.log('Nothing to prune.');
}

function help(): void {
  console.log(`bun devenv <command> [name] [options]

  up      Create a Neon branch off \`${DEFAULT_PARENT_BRANCH}\` and start the API
  down    Stop the API and delete the Neon branch
  list    Show every environment on this machine
  url     Print this environment's DATABASE_URL and API URL
  prune   Remove environments whose worktree no longer exists

Options
  --name <slug>    Environment name (default: current git branch)
  --parent <name>  Neon branch to fork from (default: ${DEFAULT_PARENT_BRANCH})
  --detach, -d     Run the API in the background
  --keep-branch    On \`down\`, keep the Neon branch
  --json           Machine-readable output for \`list\` and \`url\`
`);
}

const args = parseArgs(process.argv.slice(2));
try {
  if (args.command === 'up') await up(args);
  else if (args.command === 'down') await down(args);
  else if (args.command === 'list') list(args);
  else if (args.command === 'url') url(args);
  else if (args.command === 'prune') await prune();
  else help();
} catch (error) {
  console.error(`\n✗ ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
}
